/* The backs of the cards.
 *
 * Six designs, generated by tools/gen-card-back.mjs into public/cards/ and
 * worn by every face-down card on the felt: an opponent's hole cards at 42×60,
 * and the hero's and the board's at 66×94 for the moment before they turn.
 * Like the table's skin (./table-styles) it is a device preference — what this
 * screen looks like, seen by nobody else at the table.
 *
 * A row here needs its image at /cards/back-<id>.webp, and the same id in the
 * generator's DESIGNS so the file can be made again.
 */
import { FELT_DEEP } from './palette';

export type CardBack = { id: string; name: string; note: string };

export const CARD_BACKS: CardBack[] = [
  { id: 'lozenge', name: 'Lozenge', note: 'A suited diamond on a fine lattice.' },
  { id: 'deco', name: 'Deco', note: 'Art deco rays from a cut violet stone.' },
  { id: 'argyle', name: 'Argyle', note: 'Bright argyle around a compass star, the loudest of the six.' },
  { id: 'filigree', name: 'Filigree', note: 'Scrollwork around a violet diamond, in the manner of a casino deck.' },
  { id: 'ripple', name: 'Ripple', note: 'One lit diamond, and its outline rippling out to the edges.' },
  { id: 'suits', name: 'Suits', note: 'The four suits tiled around a solid diamond.' },
];

export const DEFAULT_CARD_BACK = 'filigree';
export const CARD_BACK_KEY = 'suited:card-back';

export const cardBack = (id: unknown): CardBack =>
  CARD_BACKS.find((b) => b.id === id) || CARD_BACKS.find((b) => b.id === DEFAULT_CARD_BACK)!;

/** The stored choice, or the default where storage is blocked or holds a back
 *  that no longer exists. */
export function storedCardBack(): string {
  try { return cardBack(localStorage.getItem(CARD_BACK_KEY)).id; } catch { return DEFAULT_CARD_BACK; }
}

/** The `background` of a face-down card. Root-relative, because the felt's
 *  route is two segments deep (/table/<id>) and a relative path would 404
 *  there. The colour under it is what shows until the image has loaded. */
export const cardBackCss = (b: CardBack): string =>
  `background:${FELT_DEEP} center/cover no-repeat url(/cards/back-${b.id}.webp)`;

/** A thumbnail for the pickers: the card itself, at the felt's own proportions. */
export const cardBackSwatchCss = (b: CardBack): string =>
  `display:block;flex:none;width:33px;height:47px;border-radius:4px;${cardBackCss(b)};box-shadow:inset 0 0 0 1px rgba(232,236,248,0.26)`;
