// suited — sampled sound, with the old synthesiser kept underneath it.
//
// The set in public/sounds/ is recorded foley generated by ElevenLabs; see
// tools/gen-sounds.mjs, which is run by hand and is not part of the build.
//
// This used to say "no files, no network", and that was its whole design. It
// is not true any more, so three things are arranged to keep the promise that
// mattered — that sound never blocks a hand:
//
//  • Nothing is fetched until a sound is actually asked for. The app starts
//    UNMUTED (`soundDefault` defaults to true), so loading on unmute would
//    mean every visitor downloading the whole set during first paint whether
//    or not they ever heard it. `play()` is the trigger instead, which is a
//    hover or a click — the first one of those is answered by the fallback,
//    and everything after it is sampled.
//  • Decoding happens once, off the hot path, into AudioBuffers.
//  • A voice whose sample is missing, still loading, or undecodable falls
//    through to the synthesised version below, which needs neither. The game
//    is never silent because a request was slow.
//
// Muted until the player asks for it; browsers require a gesture anyway.

/** Where gen-sounds.mjs writes, and the only place samples are read from. */
const DIR = '/sounds';

/* Relative loudness, applied AFTER each clip is peak-normalised at decode.
 * Normalising alone makes everything equally loud, which is wrong — a hover
 * tick and a jackpot fanfare should not sit at the same level. These say where
 * each voice belongs in the mix, and they are the knob to turn when something
 * is too loud: no regeneration, no API key, just a number. */
/* How far a clip may be amplified.
 *
 * Two earlier versions of this tried to cap the lift so that a quiet clip's
 * hiss would not become audible — first a flat 6×, then a limit derived from
 * the clip's measured noise floor. Both were wrong, and wrong for the same
 * reason: **gain does not change signal-to-noise ratio.** Lifting a clip
 * raises its content and its hiss by the identical factor, so a clip that
 * hisses at one level hisses at every level. All a cap achieves is a quieter
 * clip that hisses just as much — it hides nothing and costs audibility.
 *
 * What a clip's noise will be after normalisation is fixed before we touch it:
 *
 *     noise at peak 0.9  =  0.9 × floor / peak
 *
 * which depends only on the recording. So there is no noise-based cap here.
 * A clip too hissy to use needs a better prompt, not less gain, and
 * tools/probe-sound.mjs reports that figure so the ones worth redoing are
 * visible.
 *
 * ABSOLUTE remains, for a different reason: below some level a clip's
 * "content" is itself noise, and multiplying it by a thousand would make an
 * accident loud. 40× is about -32 dB of headroom, past which the honest answer
 * is that the generation failed. */
const ABSOLUTE = 40;

const MIX: Record<string, number> = {
  hover: 0.22,
  ui: 0.45, lowTime: 0.5, peel: 0.5,
  deal: 0.6, flip: 0.6, chip: 0.6, check: 0.6, seat: 0.6, error: 0.55, fold: 0.6, turnStart: 0.6,
  chips: 0.7, bet: 0.7, lose: 0.65, badbeat: 0.65,
  alert: 0.8, win: 0.85, allin: 0.9, potwin: 0.9,
  bigwin: 1,
};

export function createSound() {
  let ctx = null, master = null, noise = null;
  let muted = true, volume = 0.55;
  /** name → { buf, offset, gain } once decoded. Absent until then. */
  const bank = new Map();
  let loading = false;

  function ensure() {
    if (ctx) return ctx;
    const AC = window.AudioContext || window.webkitAudioContext;
    if (!AC) return null;
    ctx = new AC();
    master = ctx.createGain();
    master.gain.value = muted ? 0 : volume;
    master.connect(ctx.destination);
    const len = ctx.sampleRate * 0.6;
    noise = ctx.createBuffer(1, len, ctx.sampleRate);
    const d = noise.getChannelData(0);
    for (let i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * (1 - i / len);
    return ctx;
  }

  /* Where the clip actually starts making noise.
   *
   * Generated foley arrives with a little silence in front of it, and for a
   * card landing that silence is latency: the sound lands after the card has
   * visibly stopped. Rather than trimming the files — which would need a tool
   * this machine does not have, and would bake the decision in — the first
   * audible sample is found here and playback starts there.
   *
   * The threshold is deliberately low. Too high and the attack itself gets
   * skipped, which is worse than a few milliseconds of silence: a click with
   * its transient cut off stops sounding like a click at all. */
  function leadIn(buf) {
    const d = buf.getChannelData(0);
    const limit = Math.min(d.length, Math.floor(buf.sampleRate * 0.5));
    for (let i = 0; i < limit; i++) if (Math.abs(d[i]) > 0.01) return Math.max(0, (i - 64) / buf.sampleRate);
    return 0;
  }

  /** Peak of the whole clip, so every voice starts from the same place. */
  function peak(buf) {
    let p = 0;
    for (let c = 0; c < buf.numberOfChannels; c++) {
      const d = buf.getChannelData(c);
      for (let i = 0; i < d.length; i++) { const v = Math.abs(d[i]); if (v > p) p = v; }
    }
    return p;
  }

  /* Fetch and decode every sample, once, in the background.
   *
   * Failures are per-voice and silent on purpose: one 404 must not cost the
   * other twenty their sound, and a missing file already has a working answer
   * in the synthesiser. Nothing here is awaited by `play`. */
  function load() {
    if (loading || !ctx) return;
    loading = true;
    for (const name of Object.keys(voices)) {
      fetch(`${DIR}/${name}.mp3`)
        .then((r) => (r.ok ? r.arrayBuffer() : Promise.reject(new Error(String(r.status)))))
        .then((b) => ctx.decodeAudioData(b))
        .then((buf) => {
          /* Normalise to a common peak, then place it in the mix. A silent
             clip keeps unity gain rather than dividing by zero. */
          const p = peak(buf);
          const want = p > 0.001 ? 0.9 / p : 1;
          bank.set(name, {
            buf,
            offset: leadIn(buf),
            gain: Math.min(want, ABSOLUTE) * (MIX[name] ?? 0.6),
          });
        })
        .catch(() => { /* this voice stays synthesised */ });
    }
  }

  function sample(name) {
    const s = bank.get(name);
    if (!s) return false;
    const src = ctx.createBufferSource();
    src.buffer = s.buf;
    const g = ctx.createGain();
    g.gain.value = s.gain;
    src.connect(g); g.connect(master);
    src.start(ctx.currentTime, s.offset);
    return true;
  }

  /* ── the synthesised set, unchanged ────────────────────────────────────────
     Still here as the fallback described at the top of the file: a few
     oscillators and a noise buffer, needing no network and no decode. */
  const env = (node, t, a, dTime, peakGain) => {
    const g = ctx.createGain();
    g.gain.setValueAtTime(0.0001, t);
    g.gain.exponentialRampToValueAtTime(peakGain, t + a);
    g.gain.exponentialRampToValueAtTime(0.0001, t + a + dTime);
    node.connect(g); g.connect(master);
    return g;
  };

  function tone(freq, { at = 0, a = 0.004, d = 0.09, peak: pk = 0.22, type = 'triangle', detune = 0, sweep = null } = {}) {
    const t = ctx.currentTime + at;
    const o = ctx.createOscillator();
    o.type = type; o.frequency.setValueAtTime(freq, t);
    if (sweep) o.frequency.exponentialRampToValueAtTime(sweep, t + a + d);
    o.detune.value = detune;
    env(o, t, a, d, pk);
    o.start(t); o.stop(t + a + d + 0.05);
  }

  function hiss({ at = 0, d = 0.12, peak: pk = 0.14, hp = 900, lp = 6000, q = 0.7 } = {}) {
    const t = ctx.currentTime + at;
    const src = ctx.createBufferSource(); src.buffer = noise;
    const f1 = ctx.createBiquadFilter(); f1.type = 'highpass'; f1.frequency.value = hp; f1.Q.value = q;
    const f2 = ctx.createBiquadFilter(); f2.type = 'lowpass'; f2.frequency.value = lp;
    src.connect(f1); f1.connect(f2);
    env(f2, t, 0.006, d, pk);
    src.start(t); src.stop(t + d + 0.1);
  }

  const voices = {
    ui: () => { tone(1180, { d: 0.035, peak: 0.1, type: 'square' }); },
    hover: () => { tone(1560, { d: 0.02, peak: 0.035, type: 'sine' }); },
    deal: () => { hiss({ d: 0.1, peak: 0.1, hp: 1400, lp: 7200 }); tone(320, { d: 0.05, peak: 0.05, sweep: 210 }); },
    flip: () => { hiss({ d: 0.06, peak: 0.09, hp: 2200, lp: 9000 }); tone(760, { d: 0.05, peak: 0.07, sweep: 520 }); },
    peel: () => { hiss({ d: 0.22, peak: 0.05, hp: 3000, lp: 11000, q: 1.4 }); },
    chip: () => {
      hiss({ d: 0.05, peak: 0.13, hp: 2600, lp: 11000 });
      tone(1420, { d: 0.05, peak: 0.09, type: 'square', detune: -8 });
      tone(2100, { at: 0.02, d: 0.05, peak: 0.05, type: 'square' });
    },
    chips: () => { for (let i = 0; i < 4; i++) { hiss({ at: i * 0.035, d: 0.05, peak: 0.1, hp: 2400, lp: 10000 }); tone(1200 + i * 130, { at: i * 0.035, d: 0.05, peak: 0.06, type: 'square' }); } },
    check: () => { tone(180, { d: 0.09, peak: 0.2, type: 'sine' }); hiss({ d: 0.04, peak: 0.06, hp: 300, lp: 1800 }); },
    fold: () => { hiss({ d: 0.18, peak: 0.07, hp: 700, lp: 3400 }); tone(240, { d: 0.1, peak: 0.05, sweep: 150 }); },
    bet: () => { tone(520, { d: 0.08, peak: 0.14, sweep: 720 }); voices.chip(); },
    allin: () => { [440, 587, 740].forEach((f, i) => tone(f, { at: i * 0.06, d: 0.3, peak: 0.13, type: 'triangle' })); voices.chips(); },
    turnStart: () => { tone(880, { d: 0.07, peak: 0.09 }); tone(1320, { at: 0.05, d: 0.07, peak: 0.06 }); },
    alert: () => {
      [740, 988, 1318].forEach((f, i) => tone(f, { at: i * 0.11, d: 0.26, peak: 0.2, type: 'triangle' }));
      [740, 988].forEach((f, i) => tone(f, { at: 0.42 + i * 0.11, d: 0.26, peak: 0.16, type: 'triangle' }));
    },
    lowTime: () => { tone(660, { d: 0.06, peak: 0.12, type: 'square' }); },
    win: () => { [523, 659, 784, 1046].forEach((f, i) => tone(f, { at: i * 0.075, d: 0.34, peak: 0.15, type: 'triangle' })); voices.chips(); },
    potwin: () => {
      tone(131, { d: 0.6, peak: 0.16, type: 'sine' });
      [392, 523, 659, 784].forEach((f, i) => tone(f, { at: 0.04 + i * 0.08, d: 0.42, peak: 0.15, type: 'triangle' }));
      for (let i = 0; i < 7; i++) setTimeout(() => { if (ctx && !muted) voices.chip(); }, 120 + i * 62);
    },
    bigwin: () => {
      tone(98, { d: 0.9, peak: 0.18, type: 'sine' });
      tone(196, { d: 0.8, peak: 0.12, type: 'sine' });
      [392, 523, 659, 784, 1046, 1318, 1568].forEach((f, i) => tone(f, { at: 0.05 + i * 0.075, d: 0.62, peak: 0.16, type: 'triangle' }));
      [523, 659, 784, 1046].forEach((f, i) => tone(f, { at: 0.62 + i * 0.05, d: 0.9, peak: 0.1, type: 'sine' }));
      hiss({ at: 0.05, d: 0.9, peak: 0.05, hp: 4200, lp: 13000, q: 0.8 });
      for (let i = 0; i < 16; i++) setTimeout(() => { if (ctx && !muted) voices.chip(); }, 160 + i * 58);
    },
    lose: () => { [392, 330].forEach((f, i) => tone(f, { at: i * 0.11, d: 0.3, peak: 0.1, type: 'sine' })); },
    badbeat: () => { [523, 466, 415, 349].forEach((f, i) => tone(f, { at: i * 0.13, d: 0.4, peak: 0.11, type: 'sine' })); },
    seat: () => { tone(300, { d: 0.12, peak: 0.14, sweep: 480 }); },
    error: () => { tone(200, { d: 0.14, peak: 0.14, type: 'square', sweep: 140 }); },
  };

  return {
    play(name) {
      if (muted) return;
      if (!ensure()) return;
      if (ctx.state === 'suspended') ctx.resume();
      load();
      // The sample if it is ready, the synthesiser if it is not. An unknown
      // name still lands on the UI click, as it always did.
      if (sample(name)) return;
      (voices[name] || voices.ui)();
    },
    unlock() {
      if (muted) return;
      ensure();
      if (ctx && ctx.state === 'suspended') ctx.resume();
      // Warm the bank here rather than on the first play, so the sound that
      // announces itself is a sample and not the fallback.
      load();
    },
    setMuted(m) {
      muted = m;
      /* Deliberately does NOT start loading. This runs once on mount with the
         app's default, which is unmuted, so loading here would fetch the whole
         set during first paint for a visitor who may never make a sound. */
      if (!m) { ensure(); if (ctx && ctx.state === 'suspended') ctx.resume(); }
      if (master) master.gain.value = m ? 0 : volume;
      return muted;
    },
    setVolume(v) {
      volume = Math.max(0, Math.min(1, v));
      if (master && !muted) master.gain.value = volume;
      return volume;
    },
    /* Close the audio context and forget it.
     *
     * componentWillUnmount has always called this — "release the audio context
     * outright — a detached instance that keeps one open stays audible and
     * ignores the new instance's mute" — but it was never written, so the call
     * threw. Nothing noticed, because under the old runtime the app mounted
     * once and never unmounted; React's development double-mount is what made
     * an unmount happen at all, and with it the crash.
     *
     * The decoded bank goes with the context: an AudioBuffer belongs to the
     * context that decoded it and cannot be played through another one. */
    destroy() {
      if (ctx && typeof ctx.close === 'function') ctx.close().catch(() => {});
      ctx = null; master = null; noise = null;
      bank.clear();
      loading = false;
    },
    get muted() { return muted; },
    get volume() { return volume; },
  };
}
